// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiAmortizacion.Entidades;

public partial class Amortizacion
{
    public int Id { get; set; }

    public decimal? MontoPrestado { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public int? IdCliente { get; set; }

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual ICollection<PlanAmortizacion> PlanAmortizacion { get; set; } = new List<PlanAmortizacion>();
}