// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiAmortizacion.Entidades;

public partial class Cliente
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string NumeroIdentidad { get; set; }

    public virtual ICollection<Amortizacion> Amortizacion { get; set; } = new List<Amortizacion>();
}