// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ApiAmortizacion.Entidades;

public partial class ContextoDB : DbContext
{
    public ContextoDB(DbContextOptions<ContextoDB> options)
        : base(options)
    {
    }
    public virtual DbSet<Amortizacion> Amortizacion { get; set; }

    public virtual DbSet<Cliente> Cliente { get; set; }

    public virtual DbSet<PlanAmortizacion> PlanAmortizacion { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Amortizacion>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Amortiza__3214EC07C565FEB7");

            entity.Property(e => e.FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.MontoPrestado).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.IdClienteNavigation).WithMany(p => p.Amortizacion)
                .HasForeignKey(d => d.IdCliente)
                .HasConstraintName("FK__Amortizac__IdCli__267ABA7A");
        });

        modelBuilder.Entity<Cliente>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Cliente__3214EC077D912016");

            entity.Property(e => e.Nombre)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.NumeroIdentidad)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<PlanAmortizacion>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PlanAmor__3214EC070ABCD533");

            entity.Property(e => e.Capital).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.FechaPago).HasColumnType("date");
            entity.Property(e => e.Interes).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.PagoNiveladoConSvsd)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("PagoNiveladoConSVSD");
            entity.Property(e => e.PagoNiveladoSinSvsd)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("PagoNiveladoSinSVSD");
            entity.Property(e => e.SaldoCapital).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.IdAmortizacionNavigation).WithMany(p => p.PlanAmortizacion)
                .HasForeignKey(d => d.IdAmortizacion)
                .HasConstraintName("FK__PlanAmort__IdAmo__29572725");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}