// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiAmortizacion.Entidades;

public partial class PlanAmortizacion
{
    public int Id { get; set; }

    public int? NumeroCuota { get; set; }

    public DateTime? FechaPago { get; set; }

    public int? Dias { get; set; }

    public decimal? Interes { get; set; }

    public decimal? Capital { get; set; }

    public decimal? PagoNiveladoSinSvsd { get; set; }

    public decimal? PagoNiveladoConSvsd { get; set; }

    public decimal? SaldoCapital { get; set; }

    public int? IdAmortizacion { get; set; }

    public virtual Amortizacion IdAmortizacionNavigation { get; set; }
}